//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Periode_2.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Periode_2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _691 {
            get {
                object obj = ResourceManager.GetObject("_691", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à H
        ///He
        ///Li
        ///Be
        ///B
        ///C
        ///N
        ///O
        ///F
        ///Ne
        ///Na
        ///Mg
        ///Al
        ///Si
        ///P
        ///S
        ///Cl
        ///Ar
        ///K
        ///Ca
        ///Sc
        ///Ti
        ///V
        ///Cr
        ///Mn
        ///Fe
        ///Co
        ///Ni
        ///Cu
        ///Zn
        ///Ga
        ///Ge
        ///As
        ///Se
        ///Br
        ///Kr
        ///Rb
        ///Sr
        ///Y
        ///Zr
        ///Nb
        ///Mo
        ///Tc
        ///Ru
        ///Rh
        ///Pd
        ///Ag
        ///Cd
        ///In
        ///Sn
        ///Sb
        ///Te
        ///I
        ///Xe
        ///Cs
        ///Ba
        ///La
        ///Ce
        ///Pr
        ///Nd
        ///Pm
        ///Sm
        ///Eu
        ///Gd
        ///Tb
        ///Dy
        ///Ho
        ///Er
        ///Tm
        ///Yb
        ///Lu
        ///Hf
        ///Ta
        ///W
        ///Re
        ///Os
        ///Ir
        ///Pt
        ///Au
        ///Hg
        ///Tl
        ///Pb
        ///Bi
        ///Po
        ///At
        ///Rn
        ///Fr
        ///Ra
        ///Ac
        ///Th
        ///Pa
        ///U
        ///Np
        ///Pu
        ///Am
        ///Cm
        ///Bk
        ///Cf
        ///Es
        ///Fm
        ///Md
        ///No
        ///Lr
        ///Rf
        ///Db
        ///Sg
        ///Bh
        ///Hs
        ///Mt
        ///Ds
        ///Rg
        ///Cn
        ///Nh
        ///Fl
        ///Mc
        ///Lv
        ///Ts
        ///Og.
        /// </summary>
        internal static string Abbr {
            get {
                return ResourceManager.GetString("Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1766
        ///1895
        ///1817
        ///1797
        ///1808
        ///inconnue
        ///1772
        ///1774
        ///1886
        ///1898
        ///1807
        ///1755
        ///1825
        ///1824
        ///1669
        ///inconnue
        ///1774
        ///1894
        ///1807
        ///1808
        ///1879
        ///1791
        ///1801
        ///1797
        ///1774
        ///inconnue
        ///1735
        ///1751
        ///inconnue
        ///inconnue
        ///1875
        ///1886
        ///v. 1250
        ///1817
        ///1826
        ///1898
        ///1861
        ///1790
        ///1794
        ///1789
        ///1801
        ///1778
        ///1937
        ///1844
        ///1803
        ///1803
        ///inconnue
        ///1817
        ///1863
        ///inconnue
        ///inconnue
        ///1782
        ///1811
        ///1898
        ///1860
        ///1808
        ///1839
        ///1803
        ///1895
        ///1895
        ///1945
        ///1879
        ///1901
        ///1880
        ///1843
        ///1886
        ///1879
        ///1842
        ///1879
        ///1878
        ///1907
        ///1923
        ///1802
        ///1783
        ///1925
        ///1803
        ///1803
        ///1557
        ///inconnue        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string annee {
            get {
                return ResourceManager.GetString("annee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cavendish 
        ///Ramsay et Cleve 
        ///Arfvedson 
        ///Vauquelin 
        ///Davy et Gay-Lussac 
        ///inconnu 
        ///Rutherford 
        ///Priestley et Scheele 
        ///Moissan 
        ///Ramsay et Travers 
        ///Davy 
        ///Black 
        ///Ørsted 
        ///Berzelius 
        ///Brand 
        ///inconnu 
        ///Scheele 
        ///Ramsay et Rayleigh 
        ///Davy 
        ///Davy 
        ///Nilson 
        ///Gregor et Klaproth 
        ///del Río 
        ///Vauquelin 
        ///Gahn 
        ///inconnu 
        ///Brand 
        ///Cronstedt 
        ///inconnu 
        ///inconnu 
        ///Lecoq de Boisbaudran 
        ///Winkler 
        ///Albert le Grand 
        ///Berzelius 
        ///Balard 
        ///Ramsay et Travers 
        ///Bunsen et Kirchhoff 
        ///Crawford 
        ///Gadolin 
        ///Klaproth 
        ///Hatchet [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string decouverte {
            get {
                return ResourceManager.GetString("decouverte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1
        ///18
        ///1
        ///2
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18
        ///1
        ///2
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18
        ///1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18
        ///1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18
        ///1
        ///2
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18
        ///1
        ///2
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17.
        /// </summary>
        internal static string Groupe {
            get {
                return ResourceManager.GetString("Groupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Liquid_hydrogen_bubblechamber.jpg/330px-Liquid_hydrogen_bubblechamber.jpg
        ///https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Liquid_helium_superfluid_phase.jpg/330px-Liquid_helium_superfluid_phase.jpg
        ///https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Lithium_paraffin.jpg/330px-Lithium_paraffin.jpg
        ///https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Beryllium_nuggets_2.jpg/330px-Beryllium_nuggets_2.jpg
        ///https://upload.wikimedia [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_1 {
            get {
                object obj = ResourceManager.GetObject("image_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_10 {
            get {
                object obj = ResourceManager.GetObject("image_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_100 {
            get {
                object obj = ResourceManager.GetObject("image_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_101 {
            get {
                object obj = ResourceManager.GetObject("image_101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_102 {
            get {
                object obj = ResourceManager.GetObject("image_102", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_103 {
            get {
                object obj = ResourceManager.GetObject("image_103", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_104 {
            get {
                object obj = ResourceManager.GetObject("image_104", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_105 {
            get {
                object obj = ResourceManager.GetObject("image_105", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_106 {
            get {
                object obj = ResourceManager.GetObject("image_106", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_107 {
            get {
                object obj = ResourceManager.GetObject("image_107", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_108 {
            get {
                object obj = ResourceManager.GetObject("image_108", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_109 {
            get {
                object obj = ResourceManager.GetObject("image_109", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_11 {
            get {
                object obj = ResourceManager.GetObject("image_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_110 {
            get {
                object obj = ResourceManager.GetObject("image_110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_111 {
            get {
                object obj = ResourceManager.GetObject("image_111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_112 {
            get {
                object obj = ResourceManager.GetObject("image_112", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_113 {
            get {
                object obj = ResourceManager.GetObject("image_113", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_114 {
            get {
                object obj = ResourceManager.GetObject("image_114", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_115 {
            get {
                object obj = ResourceManager.GetObject("image_115", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_116 {
            get {
                object obj = ResourceManager.GetObject("image_116", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_117 {
            get {
                object obj = ResourceManager.GetObject("image_117", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_118 {
            get {
                object obj = ResourceManager.GetObject("image_118", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_12 {
            get {
                object obj = ResourceManager.GetObject("image_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_13 {
            get {
                object obj = ResourceManager.GetObject("image_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_14 {
            get {
                object obj = ResourceManager.GetObject("image_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_15 {
            get {
                object obj = ResourceManager.GetObject("image_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_16 {
            get {
                object obj = ResourceManager.GetObject("image_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_17 {
            get {
                object obj = ResourceManager.GetObject("image_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_18 {
            get {
                object obj = ResourceManager.GetObject("image_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_19 {
            get {
                object obj = ResourceManager.GetObject("image_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_2 {
            get {
                object obj = ResourceManager.GetObject("image_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_20 {
            get {
                object obj = ResourceManager.GetObject("image_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_21 {
            get {
                object obj = ResourceManager.GetObject("image_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_22 {
            get {
                object obj = ResourceManager.GetObject("image_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_23 {
            get {
                object obj = ResourceManager.GetObject("image_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_24 {
            get {
                object obj = ResourceManager.GetObject("image_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_25 {
            get {
                object obj = ResourceManager.GetObject("image_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_26 {
            get {
                object obj = ResourceManager.GetObject("image_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_27 {
            get {
                object obj = ResourceManager.GetObject("image_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_28 {
            get {
                object obj = ResourceManager.GetObject("image_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_29 {
            get {
                object obj = ResourceManager.GetObject("image_29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_3 {
            get {
                object obj = ResourceManager.GetObject("image_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_30 {
            get {
                object obj = ResourceManager.GetObject("image_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_31 {
            get {
                object obj = ResourceManager.GetObject("image_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_32 {
            get {
                object obj = ResourceManager.GetObject("image_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_33 {
            get {
                object obj = ResourceManager.GetObject("image_33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_34 {
            get {
                object obj = ResourceManager.GetObject("image_34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_35 {
            get {
                object obj = ResourceManager.GetObject("image_35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_36 {
            get {
                object obj = ResourceManager.GetObject("image_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_37 {
            get {
                object obj = ResourceManager.GetObject("image_37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_38 {
            get {
                object obj = ResourceManager.GetObject("image_38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_39 {
            get {
                object obj = ResourceManager.GetObject("image_39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_4 {
            get {
                object obj = ResourceManager.GetObject("image_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_40 {
            get {
                object obj = ResourceManager.GetObject("image_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_41 {
            get {
                object obj = ResourceManager.GetObject("image_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_42 {
            get {
                object obj = ResourceManager.GetObject("image_42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_43 {
            get {
                object obj = ResourceManager.GetObject("image_43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_44 {
            get {
                object obj = ResourceManager.GetObject("image_44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_45 {
            get {
                object obj = ResourceManager.GetObject("image_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_46 {
            get {
                object obj = ResourceManager.GetObject("image_46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_47 {
            get {
                object obj = ResourceManager.GetObject("image_47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_48 {
            get {
                object obj = ResourceManager.GetObject("image_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_49 {
            get {
                object obj = ResourceManager.GetObject("image_49", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_5 {
            get {
                object obj = ResourceManager.GetObject("image_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_50 {
            get {
                object obj = ResourceManager.GetObject("image_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_51 {
            get {
                object obj = ResourceManager.GetObject("image_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_52 {
            get {
                object obj = ResourceManager.GetObject("image_52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_53 {
            get {
                object obj = ResourceManager.GetObject("image_53", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_54 {
            get {
                object obj = ResourceManager.GetObject("image_54", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_55 {
            get {
                object obj = ResourceManager.GetObject("image_55", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_56 {
            get {
                object obj = ResourceManager.GetObject("image_56", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_57 {
            get {
                object obj = ResourceManager.GetObject("image_57", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_58 {
            get {
                object obj = ResourceManager.GetObject("image_58", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_59 {
            get {
                object obj = ResourceManager.GetObject("image_59", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_6 {
            get {
                object obj = ResourceManager.GetObject("image_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_60 {
            get {
                object obj = ResourceManager.GetObject("image_60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_61 {
            get {
                object obj = ResourceManager.GetObject("image_61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_62 {
            get {
                object obj = ResourceManager.GetObject("image_62", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_63 {
            get {
                object obj = ResourceManager.GetObject("image_63", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_64 {
            get {
                object obj = ResourceManager.GetObject("image_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_65 {
            get {
                object obj = ResourceManager.GetObject("image_65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_66 {
            get {
                object obj = ResourceManager.GetObject("image_66", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_67 {
            get {
                object obj = ResourceManager.GetObject("image_67", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_68 {
            get {
                object obj = ResourceManager.GetObject("image_68", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_69 {
            get {
                object obj = ResourceManager.GetObject("image_69", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_7 {
            get {
                object obj = ResourceManager.GetObject("image_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_70 {
            get {
                object obj = ResourceManager.GetObject("image_70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_71 {
            get {
                object obj = ResourceManager.GetObject("image_71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_72 {
            get {
                object obj = ResourceManager.GetObject("image_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_73 {
            get {
                object obj = ResourceManager.GetObject("image_73", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_74 {
            get {
                object obj = ResourceManager.GetObject("image_74", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_75 {
            get {
                object obj = ResourceManager.GetObject("image_75", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_76 {
            get {
                object obj = ResourceManager.GetObject("image_76", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_77 {
            get {
                object obj = ResourceManager.GetObject("image_77", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_78 {
            get {
                object obj = ResourceManager.GetObject("image_78", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_79 {
            get {
                object obj = ResourceManager.GetObject("image_79", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_8 {
            get {
                object obj = ResourceManager.GetObject("image_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_80 {
            get {
                object obj = ResourceManager.GetObject("image_80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_81 {
            get {
                object obj = ResourceManager.GetObject("image_81", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_82 {
            get {
                object obj = ResourceManager.GetObject("image_82", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_83 {
            get {
                object obj = ResourceManager.GetObject("image_83", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_84 {
            get {
                object obj = ResourceManager.GetObject("image_84", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_85 {
            get {
                object obj = ResourceManager.GetObject("image_85", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_86 {
            get {
                object obj = ResourceManager.GetObject("image_86", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_87 {
            get {
                object obj = ResourceManager.GetObject("image_87", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_88 {
            get {
                object obj = ResourceManager.GetObject("image_88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_89 {
            get {
                object obj = ResourceManager.GetObject("image_89", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_9 {
            get {
                object obj = ResourceManager.GetObject("image_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_90 {
            get {
                object obj = ResourceManager.GetObject("image_90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_91 {
            get {
                object obj = ResourceManager.GetObject("image_91", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_92 {
            get {
                object obj = ResourceManager.GetObject("image_92", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_93 {
            get {
                object obj = ResourceManager.GetObject("image_93", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_94 {
            get {
                object obj = ResourceManager.GetObject("image_94", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_95 {
            get {
                object obj = ResourceManager.GetObject("image_95", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_96 {
            get {
                object obj = ResourceManager.GetObject("image_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_97 {
            get {
                object obj = ResourceManager.GetObject("image_97", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_98 {
            get {
                object obj = ResourceManager.GetObject("image_98", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_99 {
            get {
                object obj = ResourceManager.GetObject("image_99", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image1 {
            get {
                object obj = ResourceManager.GetObject("image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        internal static System.Drawing.Icon image2 {
            get {
                object obj = ResourceManager.GetObject("image2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hydrogène
        ///Hélium
        ///Lithium
        ///Béryllium
        ///Bore
        ///Carbone
        ///Azote
        ///Oxygène
        ///Fluor
        ///Néon
        ///Sodium
        ///Magnésium
        ///Aluminium
        ///Silicium
        ///Phosphore
        ///Soufre
        ///Chlore
        ///Argon
        ///Potassium
        ///Calcium
        ///Scandium
        ///Titane
        ///Vanadium
        ///Chrome
        ///Manganèse
        ///Fer
        ///Cobalt
        ///Nickel
        ///Cuivre
        ///Zinc
        ///Gallium
        ///Germanium
        ///Arsenic
        ///Sélénium
        ///Brome
        ///Krypton
        ///Rubidium
        ///Strontium
        ///Yttrium
        ///Zirconium
        ///Niobium
        ///Molybdène
        ///Technétium
        ///Ruthénium
        ///Rhodium
        ///Palladium
        ///Argent
        ///Cadmium
        ///Indium
        ///Étain
        ///Antimoine
        ///Tellure
        ///Iode
        ///Xénon
        ///Césium
        ///Baryum
        ///Lanthane
        ///Cér [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string liste {
            get {
                return ResourceManager.GetString("liste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1,007 94 g/mol
        ///4,002 602 g/mol
        ///6,941 g/mol
        ///9,012 182 g/mol
        ///10,811 g/mol
        ///12,011 g/mol
        ///14,006 74 g/mol
        ///15,999 4 g/mol
        ///18,998 403 2 g/mol
        ///20,179 7 g/mol
        ///22,989 768 g/mol
        ///24,305 g/mol
        ///26,981 539 g/mol
        ///28,085 5 g/mol
        ///30,973 762 g/mol
        ///32,066 g/mol
        ///35,452 7 g/mol
        ///39,948 g/mol
        ///39,098 3 g/mol
        ///40,078 g/mol
        ///44,955 91 g/mol
        ///47,88 g/mol
        ///50,941 5 g/mol
        ///51,996 1 g/mol
        ///54,938 05 g/mol
        ///55,847 g/mol
        ///58,933 2 g/mol
        ///58,69 g/mol
        ///63,546 g/mol
        ///65,39 g/mol
        ///69,723 g/mol
        ///72,61 g/mol
        ///74,921 59 g/mol
        ///7 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string masse {
            get {
                return ResourceManager.GetString("masse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1
        ///1
        ///2
        ///2
        ///2
        ///2
        ///2
        ///2
        ///2
        ///2
        ///3
        ///3
        ///3
        ///3
        ///3
        ///3
        ///3
        ///3
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9.
        /// </summary>
        internal static string Periode {
            get {
                return ResourceManager.GetString("Periode", resourceCulture);
            }
        }
    }
}
