//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Periode_2 {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Periode_2.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _691 {
            get {
                object obj = ResourceManager.GetObject("_691", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à H
        ///He
        ///Li
        ///Be
        ///B
        ///C
        ///N
        ///O
        ///F
        ///Ne
        ///Na
        ///Mg
        ///Al
        ///Si
        ///P
        ///S
        ///Cl
        ///Ar
        ///K
        ///Ca
        ///Sc
        ///Ti
        ///V
        ///Cr
        ///Mn
        ///Fe
        ///Co
        ///Ni
        ///Cu
        ///Zn
        ///Ga
        ///Ge
        ///As
        ///Se
        ///Br
        ///Kr
        ///Rb
        ///Sr
        ///Y
        ///Zr
        ///Nb
        ///Mo
        ///Tc
        ///Ru
        ///Rh
        ///Pd
        ///Ag
        ///Cd
        ///In
        ///Sn
        ///Sb
        ///Te
        ///I
        ///Xe
        ///Cs
        ///Ba
        ///La
        ///Ce
        ///Pr
        ///Nd
        ///Pm
        ///Sm
        ///Eu
        ///Gd
        ///Tb
        ///Dy
        ///Ho
        ///Er
        ///Tm
        ///Yb
        ///Lu
        ///Hf
        ///Ta
        ///W
        ///Re
        ///Os
        ///Ir
        ///Pt
        ///Au
        ///Hg
        ///Tl
        ///Pb
        ///Bi
        ///Po
        ///At
        ///Rn
        ///Fr
        ///Ra
        ///Ac
        ///Th
        ///Pa
        ///U
        ///Np
        ///Pu
        ///Am
        ///Cm
        ///Bk
        ///Cf
        ///Es
        ///Fm
        ///Md
        ///No
        ///Lr
        ///Rf
        ///Db
        ///Sg
        ///Bh
        ///Hs
        ///Mt
        ///Ds
        ///Rg
        ///Cn
        ///Nh
        ///Fl
        ///Mc
        ///Lv
        ///Ts
        ///Og.
        /// </summary>
        internal static string Abbr {
            get {
                return ResourceManager.GetString("Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1766
        ///1895
        ///1817
        ///1797
        ///1808
        ///inconnue
        ///1772
        ///1774
        ///1886
        ///1898
        ///1807
        ///1755
        ///1825
        ///1824
        ///1669
        ///inconnue
        ///1774
        ///1894
        ///1807
        ///1808
        ///1879
        ///1791
        ///1801
        ///1797
        ///1774
        ///inconnue
        ///1735
        ///1751
        ///inconnue
        ///inconnue
        ///1875
        ///1886
        ///v. 1250
        ///1817
        ///1826
        ///1898
        ///1861
        ///1790
        ///1794
        ///1789
        ///1801
        ///1778
        ///1937
        ///1844
        ///1803
        ///1803
        ///inconnue
        ///1817
        ///1863
        ///inconnue
        ///inconnue
        ///1782
        ///1811
        ///1898
        ///1860
        ///1808
        ///1839
        ///1803
        ///1895
        ///1895
        ///1945
        ///1879
        ///1901
        ///1880
        ///1843
        ///1886
        ///1879
        ///1842
        ///1879
        ///1878
        ///1907
        ///1923
        ///1802
        ///1783
        ///1925
        ///1803
        ///1803
        ///1557
        ///inconnue
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string annee {
            get {
                return ResourceManager.GetString("annee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cavendish 
        ///Ramsay et Cleve 
        ///Arfvedson 
        ///Vauquelin 
        ///Davy et Gay-Lussac 
        ///inconnu 
        ///Rutherford 
        ///Priestley et Scheele 
        ///Moissan 
        ///Ramsay et Travers 
        ///Davy 
        ///Black 
        ///Ørsted 
        ///Berzelius 
        ///Brand 
        ///inconnu 
        ///Scheele 
        ///Ramsay et Rayleigh 
        ///Davy 
        ///Davy 
        ///Nilson 
        ///Gregor et Klaproth 
        ///del Río 
        ///Vauquelin 
        ///Gahn 
        ///inconnu 
        ///Brand 
        ///Cronstedt 
        ///inconnu 
        ///inconnu 
        ///Lecoq de Boisbaudran 
        ///Winkler 
        ///Albert le Grand 
        ///Berzelius 
        ///Balard 
        ///Ramsay et Travers 
        ///Bunsen et Kirchhoff 
        ///Crawford 
        ///Gadolin 
        ///Klaproth 
        ///Hatchet [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string decoverte {
            get {
                return ResourceManager.GetString("decoverte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1
        ///18
        ///1
        ///2
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18
        ///1
        ///2
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18
        ///1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18
        ///1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18
        ///1
        ///2
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18
        ///1
        ///2
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17.
        /// </summary>
        internal static string Groupe {
            get {
                return ResourceManager.GetString("Groupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Liquid_hydrogen_bubblechamber.jpg/330px-Liquid_hydrogen_bubblechamber.jpg
        ///https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Liquid_helium_superfluid_phase.jpg/330px-Liquid_helium_superfluid_phase.jpg
        ///https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Lithium_paraffin.jpg/330px-Lithium_paraffin.jpg
        ///https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Beryllium_nuggets_2.jpg/330px-Beryllium_nuggets_2.jpg
        ///https://upload.wikimedia [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hydrogène
        ///Hélium
        ///Lithium
        ///Béryllium
        ///Bore
        ///Carbone
        ///Azote
        ///Oxygène
        ///Fluor
        ///Néon
        ///Sodium
        ///Magnésium
        ///Aluminium
        ///Silicium
        ///Phosphore
        ///Soufre
        ///Chlore
        ///Argon
        ///Potassium
        ///Calcium
        ///Scandium
        ///Titane
        ///Vanadium
        ///Chrome
        ///Manganèse
        ///Fer
        ///Cobalt
        ///Nickel
        ///Cuivre
        ///Zinc
        ///Gallium
        ///Germanium
        ///Arsenic
        ///Sélénium
        ///Brome
        ///Krypton
        ///Rubidium
        ///Strontium
        ///Yttrium
        ///Zirconium
        ///Niobium
        ///Molybdène
        ///Technétium
        ///Ruthénium
        ///Rhodium
        ///Palladium
        ///Argent
        ///Cadmium
        ///Indium
        ///Étain
        ///Antimoine
        ///Tellure
        ///Iode
        ///Xénon
        ///Césium
        ///Baryum
        ///Lanthane
        ///Cér [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string liste {
            get {
                return ResourceManager.GetString("liste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1,007 94 g/mol
        ///4,002 602 g/mol
        ///6,941 g/mol
        ///9,012 182 g/mol
        ///10,811 g/mol
        ///12,011 g/mol
        ///14,006 74 g/mol
        ///15,999 4 g/mol
        ///18,998 403 2 g/mol
        ///20,179 7 g/mol
        ///22,989 768 g/mol
        ///24,305 g/mol
        ///26,981 539 g/mol
        ///28,085 5 g/mol
        ///30,973 762 g/mol
        ///32,066 g/mol
        ///35,452 7 g/mol
        ///39,948 g/mol
        ///39,098 3 g/mol
        ///40,078 g/mol
        ///44,955 91 g/mol
        ///47,88 g/mol
        ///50,941 5 g/mol
        ///51,996 1 g/mol
        ///54,938 05 g/mol
        ///55,847 g/mol
        ///58,933 2 g/mol
        ///58,69 g/mol
        ///63,546 g/mol
        ///65,39 g/mol
        ///69,723 g/mol
        ///72,61 g/mol
        ///74,921 59 g/mol
        ///7 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string masse {
            get {
                return ResourceManager.GetString("masse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1
        ///1
        ///2
        ///2
        ///2
        ///2
        ///2
        ///2
        ///2
        ///2
        ///3
        ///3
        ///3
        ///3
        ///3
        ///3
        ///3
        ///3
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///4
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///5
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///6
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///7
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///8
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9
        ///9.
        /// </summary>
        internal static string Periode {
            get {
                return ResourceManager.GetString("Periode", resourceCulture);
            }
        }
    }
}
